[plugin]
repository = "https://github.com/Ibcrootbeer/RetainerAlerts.git"
commit = "f09a3c98093dafd68f15244b47df47d121082dad"
owners = ["Ibcrootbeer"]
project_path = "RetainerAlerts"
changelog = "Fixed the popup always being re-positionable on startup."
